image:
  file: .gitpod.dockerfile
tasks:
 - init: pip3 install pygame
vscode:
  extensions:
    - ms-python.python
    - formulahendry.auto-close-tag
    - eventyret.bootstrap-4-cdn-snippet
    - hookyqr.beautify
    - matt-rudge.auto-open-preview-panel
ports:
  - port: 5900
    onOpen: ignore
  - port: 6080
    onOpen: open-preview
